# Generated by Django 5.0.3 on 2024-03-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='Completed_task',
            field=models.BooleanField(default=False),
        ),
    ]
