# Generated by Django 5.0.3 on 2024-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_handover_completed_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Notice', models.TextField()),
                ('Notice_by', models.CharField(max_length=300)),
            ],
        ),
    ]
