# Generated by Django 5.0.3 on 2024-03-30 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='title',
            field=models.CharField(default='Default Title', max_length=500),
        ),
        migrations.AlterField(
            model_name='handover',
            name='Handover_From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='handover',
            name='Handover_To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
