# Generated by Django 5.0.3 on 2024-04-07 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_notices_notice_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
